# Site and SEO Setup
title: Aspire
description: Aspire Dashboard for OpenTelemetry
url: "http://www.aspiredashboard.com"
#baseurl: ""
locale: en_US
lang: en
logo: /assets/img/logos.png
image: /assets/img/logos.png
favicon: /assets/img/logos.png

# Navbar Setup
navbar:
  logo: /assets/img/logos.png
  button: Get Started
  list:
    - nav: Features
      link: "#features"
    - nav: GitHub
      link: "https://github.com/dotnet/aspire"
    - nav: Docs
      link: "https://learn.microsoft.com/dotnet/aspire/fundamentals/dashboard/standalone"
    - nav: Community
      link: "#community"
    - nav: Samples
      link: "https://github.com/orgs/aspire-dashboard/repositories"

# Footer Setup
footer:
  title: Join our Aspire Dashboard community
  text: Chat with the Aspire community on integrating OpenTelemetry with the Aspire Dashboard, building distributed cloud-native apps, and so much more. Join the aspire channel under frameworks.
  button:
    - text: Join Our Discord
      icon: /assets/img/discord.svg
      link: https://aka.ms/dotnet-discord
copyrights: Copyright Â© 2024

# Social Media Setup
social:
  facebook:
  twitter:
  instagram:
  youtube:
  whatsapp:

# Jekyll Setup
collections:
  pages:
    output: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
developer:
  name: Aspire Dashboard
  hire: 
  site: 
defaults:
  - scope:
      path: assets/img
    values:
      image: true
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
    values:
      layout: default
